#
#	$Id$
#
# GU monitor whiteboard module Makefile
#
BIN=guudpwhiteboard

ALL_TARGETS=host robot

CPP_SRCS=main.cpp udp_util.cpp udp_sender.cpp udp_receiver.cpp
SPECIFIC_CPPFLAGS=-fblocks

.include "../../../mk/whiteboard.mk"
.include "../../../mk/mipal.mk"		# comes last!


