/**                                                                     
 *  /file guwhiteboardtypelist_c_typestrings_generated.c                
 *                                                                      
 *  Created by Carl Lusty in 2013.                                      
 *  Copyright (c) 2013 Carl Lusty                                       
 *  All rights reserved.                                                
 */                                                                     


//Generated on: Mon Feb 18 14:46:24 2013
//Generated by user: carl

const char *WBTypes_stringValues[] = 
{
        "gu*",
        "Print",
        "Say",
        "Speech",
        "QSay",
        "QSpeech",
        "SpeechOutput",
        "guvision_runVisionPipeline",
        "gu_whatever",
        "gu_whatever2",
        "gu_whatever3"
};      

