/**                                                                     
 *  /file guwhiteboardtypelist_c_typestrings_generated.c                
 *                                                                      
 *  Created by Carl Lusty in 2013.                                      
 *  Copyright (c) 2013 Carl Lusty                                       
 *  All rights reserved.                                                
 */                                                                     


//Generated on: Wed Feb 20 13:55:39 2013
//Generated by user: carl

const char *WBTypes_stringValues[] = 
{
        "gu*",
        "Print",
        "Say",
        "Speech",
        "QSay",
        "QSpeech",
        "SpeechOutput",
        "example_bool",
        "example_class",
        "example_type"
};      

