//Generated file, DO NOT MODIFY

#include <gusimplewhiteboard/typeClassDefs/wb_apm_interface.h>
#include <gusimplewhiteboard/typeClassDefs/wb_arrayoffilteredsonarobjects.h>
#include <gusimplewhiteboard/typeClassDefs/wb_ball.h>
#include <gusimplewhiteboard/typeClassDefs/wb_button.h>
#include <gusimplewhiteboard/typeClassDefs/wb_buttons_status.h>
#include <gusimplewhiteboard/typeClassDefs/wb_channels.h>
#include <gusimplewhiteboard/typeClassDefs/wb_clocks.h>
#include <gusimplewhiteboard/typeClassDefs/wb_count.h>
#include <gusimplewhiteboard/typeClassDefs/wb_differential_robot.h>
#include <gusimplewhiteboard/typeClassDefs/wb_fft_frequencies.h>
#include <gusimplewhiteboard/typeClassDefs/wb_field_horizon.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filtered_arrayballsightings.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filtered_arrayonedimobjects.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filtered_vision_ball_type.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filtered_vision_object.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filtered_vision_object_type.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filteredsonarobject.h>
#include <gusimplewhiteboard/typeClassDefs/wb_filteredvisionobject.h>
#include <gusimplewhiteboard/typeClassDefs/wb_fsm_control_status.h>
#include <gusimplewhiteboard/typeClassDefs/wb_fsm_state_status.h>
#include <gusimplewhiteboard/typeClassDefs/wb_giraff_main_serial.h>
#include <gusimplewhiteboard/typeClassDefs/wb_goal.h>
#include <gusimplewhiteboard/typeClassDefs/wb_hal_armtarget.h>
#include <gusimplewhiteboard/typeClassDefs/wb_hal_headtarget.h>
#include <gusimplewhiteboard/typeClassDefs/wb_hal_legtarget.h>
#include <gusimplewhiteboard/typeClassDefs/wb_input3d.h>
#include <gusimplewhiteboard/typeClassDefs/wb_io_pins.h>
#include <gusimplewhiteboard/typeClassDefs/wb_kinematic_motor.h>
#include <gusimplewhiteboard/typeClassDefs/wb_lights.h>
#include <gusimplewhiteboard/typeClassDefs/wb_lines.h>
#include <gusimplewhiteboard/typeClassDefs/wb_nao_state.h>
#include <gusimplewhiteboard/typeClassDefs/wb_nao_walk_command.h>
#include <gusimplewhiteboard/typeClassDefs/wb_nao_walk_status.h>
#include <gusimplewhiteboard/typeClassDefs/wb_nxt_interface.h>
#include <gusimplewhiteboard/typeClassDefs/wb_oculus_prime_interface.h>
#include <gusimplewhiteboard/typeClassDefs/wb_oculus_prime_serial.h>
#include <gusimplewhiteboard/typeClassDefs/wb_particle_position.h>
#include <gusimplewhiteboard/typeClassDefs/wb_point.h>
#include <gusimplewhiteboard/typeClassDefs/wb_point2d.h>
#include <gusimplewhiteboard/typeClassDefs/wb_robot.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_armjointsensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_body.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_bodysensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_foot.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_footsensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_leds.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_legjointsensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_legjointtemps.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_legs.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_legtemps.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_sonar.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_torso.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_torsojointsensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_torsojointtemps.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_torsotemps.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sound.h>
#include <gusimplewhiteboard/typeClassDefs/wb_switch_subsumption.h>
#include <gusimplewhiteboard/typeClassDefs/wb_switch_subsumption_traffic_lights.h>
#include <gusimplewhiteboard/typeClassDefs/wb_teleoperation.h>
#include <gusimplewhiteboard/typeClassDefs/wb_top_particles.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_fieldfeature.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_fieldfeatures.h>
