#
#	$Id$
#
# GU monitor whiteboard module Makefile
#
BIN=guudpbridge

ALL_TARGETS=host robot

CPP_SRCS=guudpBridgeManager.cpp guudpBridgeListener.cpp guudpBridgeBroadcaster.cpp guudpbridgenetworkutil.cpp
CPP_HDRS=guudpBridgeManager.h guudpBridgeListener.h guudpBridgeBroadcaster.h guudpbridgenetworkutil.h


.include "../../../mk/whiteboard.mk"	# required for whiteboard clients
.include "../../../mk/mipal.mk"		# comes last!
