#
#	$Id$
#
# GU monitor whiteboard module Makefile
#
BIN=guudpbridge

ALL_TARGETS=host robot

CPP_SRCS=guudpbridgemanager.cpp guudpbridgelistener.cpp guudpbridgebroadcaster.cpp
CPP_HDRS=guudpbridgemanager.h


.include "../../../mk/whiteboard.mk"	# required for whiteboard clients
.include "../../../mk/mipal.mk"		# comes last!
