#
#	$Id$
#
# GU monitor whiteboard module Makefile
#
BIN=guudpbridge

ALL_TARGETS=host robot

SPECIFIC_CPPFLAGS=-DBRIDGE_MAIN=1

.include "../../../mk/remotewhiteboard.mk"	# required for whiteboard clients
.include "../../../mk/mipal.mk"		# comes last!
