#
#       $Id$
#

BIN=guwhiteboardtypegenerator

ALL_TARGETS=host

CPP_SRCS=guwhiteboardtypegenerator.cpp
#C_SRCS=gusimplewhiteboard.c

.include "../../../mk/libcxx.mk"
.include "../../../mk/mipal.mk"            # comes last!
