/*
 * file FieldHorizon.h
 *
 * This file was generated by classgenerator from fieldHorizon.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Created by Carl Lusty at 05:09, 21/09/2017.
 * Copyright © 2017 Carl Lusty. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#ifndef FieldHorizon_DEFINED
#define FieldHorizon_DEFINED

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION
#include <cstdlib>
#include <string.h>
#include <sstream>
#endif

#include "wb_field_horizon.h"

namespace guWhiteboard {

    /**
     * Provides a C++ wrapper around `wb_field_horizon`.
     */
    class FieldHorizon: public wb_field_horizon {

    public:

        /**
         * Create a new `FieldHorizon`.
         */
        FieldHorizon(HorizonOptions horizonType = HorizonFailed, uint16_t lhp_x = 0, uint16_t lhp_y = 0, uint16_t rhp_x = 0, uint16_t rhp_y = 0, uint16_t chp_x = 0, uint16_t chp_y = 0) {
            set_horizonType(horizonType);
            set_lhp_x(lhp_x);
            set_lhp_y(lhp_y);
            set_rhp_x(rhp_x);
            set_rhp_y(rhp_y);
            set_chp_x(chp_x);
            set_chp_y(chp_y);
        }

        /**
         * Copy Constructor.
         */
        FieldHorizon(const FieldHorizon &other): wb_field_horizon() {
            set_horizonType(other.horizonType());
            set_lhp_x(other.lhp_x());
            set_lhp_y(other.lhp_y());
            set_rhp_x(other.rhp_x());
            set_rhp_y(other.rhp_y());
            set_chp_x(other.chp_x());
            set_chp_y(other.chp_y());
        }

        /**
         * Copy Assignment Operator.
         */
        FieldHorizon &operator = (const FieldHorizon &other) {
            set_horizonType(other.horizonType());
            set_lhp_x(other.lhp_x());
            set_lhp_y(other.lhp_y());
            set_rhp_x(other.rhp_x());
            set_rhp_y(other.rhp_y());
            set_chp_x(other.chp_x());
            set_chp_y(other.chp_y());
            return *this;
        }

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION
        /**
         * String Constructor.
         */
        FieldHorizon(const std::string &str) { from_string(str.c_str()); }

        std::string description() {
#ifdef USE_WB_FIELD_HORIZON_C_CONVERSION
            char buffer[FIELDHORIZON_DESC_BUFFER_SIZE];
            wb_field_horizon_description(this, buffer, sizeof(buffer));
            std::string descr = buffer;
            return descr;
#else
            std::ostringstream ss;
            ss << "horizonType=" << horizonType();
            ss << ", ";
            ss << "lhp_x=" << lhp_x();
            ss << ", ";
            ss << "lhp_y=" << lhp_y();
            ss << ", ";
            ss << "rhp_x=" << rhp_x();
            ss << ", ";
            ss << "rhp_y=" << rhp_y();
            ss << ", ";
            ss << "chp_x=" << chp_x();
            ss << ", ";
            ss << "chp_y=" << chp_y();
            return ss.str();
#endif /// USE_WB_FIELD_HORIZON_C_CONVERSION
        }
#endif // WHITEBOARD_POSTER_STRING_CONVERSION

    };

};

#endif // FieldHorizon_DEFINED
