/*
 * file FilteredVisionObject.swift
 *
 * This file was generated by classgenerator from Filtered_Vision_Object.txt.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2019 Vlad Estivill-Castro. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Vlad Estivill-Castro.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * @brief Posting by Kalman filter on object sighting
 */
extension wb_filtered_vision_object {

    /**
     * Create a new `wb_filtered_vision_object`.
     */
    public static func make() -> wb_filtered_vision_object {
        return wb_filtered_vision_object(0)
    }

    /**
     * Create a new `wb_filtered_vision_object`.
     */
    public init(_ visibilityHistory: UInt64 = 0, frameCounter: Int32 = 0, distance: Int16 = 0, x: Int16 = 0, y: Int16 = 0, yaw: Int16 = 0, ray_angle: Int16 = 0, isVisible: Bool = true, pad1: Bool = true) {
        self.init()
        self.visibilityHistory = visibilityHistory
        self.frameCounter = frameCounter
        self.distance = distance
        self.x = x
        self.y = y
        self.yaw = yaw
        self.ray_angle = ray_angle
        self.isVisible = isVisible
        self.pad1 = pad1
    }

    /**
     * Create a `wb_filtered_vision_object` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any]) {
        self.init()
        guard
            let visibilityHistory = dictionary["visibilityHistory"] as? UInt64,
            let frameCounter = dictionary["frameCounter"] as? Int32,
            let distance = dictionary["distance"] as? Int16,
            let x = dictionary["x"] as? Int16,
            let y = dictionary["y"] as? Int16,
            let yaw = dictionary["yaw"] as? Int16,
            let ray_angle = dictionary["ray_angle"] as? Int16,
            let isVisible = dictionary["isVisible"] as? Bool,
            let pad1 = dictionary["pad1"] as? Bool
        else {
            fatalError("Unable to convert \(dictionary) to wb_filtered_vision_object.")
        }
        self.visibilityHistory = visibilityHistory
        self.frameCounter = frameCounter
        self.distance = distance
        self.x = x
        self.y = y
        self.yaw = yaw
        self.ray_angle = ray_angle
        self.isVisible = isVisible
        self.pad1 = pad1
    }

}

extension wb_filtered_vision_object: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "visibilityHistory=\(self.visibilityHistory)"
        descString += ", "
        descString += "frameCounter=\(self.frameCounter)"
        descString += ", "
        descString += "distance=\(self.distance)"
        descString += ", "
        descString += "x=\(self.x)"
        descString += ", "
        descString += "y=\(self.y)"
        descString += ", "
        descString += "yaw=\(self.yaw)"
        descString += ", "
        descString += "ray_angle=\(self.ray_angle)"
        descString += ", "
        descString += "isVisible=\(self.isVisible)"
        descString += ", "
        descString += "pad1=\(self.pad1)"
        return descString
    }

}

extension wb_filtered_vision_object: Equatable {}

public func == (lhs: wb_filtered_vision_object, rhs: wb_filtered_vision_object) -> Bool {
    return lhs.visibilityHistory == rhs.visibilityHistory
        && lhs.frameCounter == rhs.frameCounter
        && lhs.distance == rhs.distance
        && lhs.x == rhs.x
        && lhs.y == rhs.y
        && lhs.yaw == rhs.yaw
        && lhs.ray_angle == rhs.ray_angle
        && lhs.isVisible == rhs.isVisible
        && lhs.pad1 == rhs.pad1
}
