/*
 * file FrequencyLimits.swift
 *
 * This file was generated by classgenerator from frequency_limits.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2019 Rene Hexel. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Rene Hexel.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * Low and high frequency limits for dominant frequency analysis
 */
extension wb_frequency_limits {

    /**
     * Create a new `wb_frequency_limits`.
     */
    public static func make() -> wb_frequency_limits {
        return wb_frequency_limits(0)
    }

    /**
     * Create a new `wb_frequency_limits`.
     */
    public init(_ lo_freq: Int16 = 0, hi_freq: Int16 = 0) {
        self.init()
        self.lo_freq = lo_freq
        self.hi_freq = hi_freq
    }

    /**
     * Create a `wb_frequency_limits` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any]) {
        self.init()
        guard
            let lo_freq = dictionary["lo_freq"] as? Int16,
            let hi_freq = dictionary["hi_freq"] as? Int16
        else {
            fatalError("Unable to convert \(dictionary) to wb_frequency_limits.")
        }
        self.lo_freq = lo_freq
        self.hi_freq = hi_freq
    }

}

extension wb_frequency_limits: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "lo_freq=\(self.lo_freq)"
        descString += ", "
        descString += "hi_freq=\(self.hi_freq)"
        return descString
    }

}

extension wb_frequency_limits: Equatable {}

public func == (lhs: wb_frequency_limits, rhs: wb_frequency_limits) -> Bool {
    return lhs.lo_freq == rhs.lo_freq
        && lhs.hi_freq == rhs.hi_freq
}
