/*
 * file VisionLines.swift
 *
 * This file was generated by classgenerator from vision_lines.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Created by Eugene Gilmore at 13:01, 22/11/2018.
 * Copyright © 2018 Eugene Gilmore. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Eugene Gilmore.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * Class use to represent lines detected by vision and posted to the whiteboard
 */
extension wb_vision_lines {

    public var _topLines: [wb_vision_line] {
        get {
            var topLines = self.topLines
            return withUnsafePointer(to: &topLines.0) { topLines_p in
                var topLines: [wb_vision_line] = []
                topLines.reserveCapacity(5)
                for topLines_index in 0..<5 {
                    topLines.append(topLines_p[topLines_index])
                }
                return topLines
            }
        } set {
            _ = withUnsafeMutablePointer(to: &self.topLines.0) { topLines_p in
                for topLines_index in 0..<5 {
                    topLines_p[topLines_index] = newValue[topLines_index]
                }
            }
        }
    }

    public var _bottomLines: [wb_vision_line] {
        get {
            var bottomLines = self.bottomLines
            return withUnsafePointer(to: &bottomLines.0) { bottomLines_p in
                var bottomLines: [wb_vision_line] = []
                bottomLines.reserveCapacity(5)
                for bottomLines_index in 0..<5 {
                    bottomLines.append(bottomLines_p[bottomLines_index])
                }
                return bottomLines
            }
        } set {
            _ = withUnsafeMutablePointer(to: &self.bottomLines.0) { bottomLines_p in
                for bottomLines_index in 0..<5 {
                    bottomLines_p[bottomLines_index] = newValue[bottomLines_index]
                }
            }
        }
    }

    /**
     * Create a new `wb_vision_lines`.
     */
    public static func make() -> wb_vision_lines {
        return wb_vision_lines([wb_vision_line(), wb_vision_line(), wb_vision_line(), wb_vision_line(), wb_vision_line()])
    }

    /**
     * Create a new `wb_vision_lines`.
     */
    public init(_ topLines: [wb_vision_line] = [wb_vision_line(), wb_vision_line(), wb_vision_line(), wb_vision_line(), wb_vision_line()], bottomLines: [wb_vision_line] = [wb_vision_line(), wb_vision_line(), wb_vision_line(), wb_vision_line(), wb_vision_line()], numTopLines: UInt8 = 0, numBottomLines: UInt8 = 0, frameNumber: UInt64 = 0) {
        self.init()
        self._topLines = topLines
        self._bottomLines = bottomLines
        self.numTopLines = numTopLines
        self.numBottomLines = numBottomLines
        self.frameNumber = frameNumber
    }

    /**
     * Create a `wb_vision_lines` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any]) {
        self.init()
        guard
            var topLines = dictionary["topLines"],
            var bottomLines = dictionary["bottomLines"],
            let numTopLines = dictionary["numTopLines"] as? UInt8,
            let numBottomLines = dictionary["numBottomLines"] as? UInt8,
            let frameNumber = dictionary["frameNumber"] as? UInt64
        else {
            fatalError("Unable to convert \(dictionary) to wb_vision_lines.")
        }
        self.topLines = withUnsafePointer(to: &topLines) {
            $0.withMemoryRebound(to: type(of: wb_vision_lines().topLines), capacity: 1) {
                $0.pointee
            }
        }
        self.bottomLines = withUnsafePointer(to: &bottomLines) {
            $0.withMemoryRebound(to: type(of: wb_vision_lines().bottomLines), capacity: 1) {
                $0.pointee
            }
        }
        self.numTopLines = numTopLines
        self.numBottomLines = numBottomLines
        self.frameNumber = frameNumber
    }

}

extension wb_vision_lines: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        if self._topLines.isEmpty {
            descString += "topLines={}"
        } else {
            let first = "{" + self.topLines.0.description + "}"
            descString += "topLines={"
            descString += self._topLines.dropFirst().reduce("\(first)") { $0 + ", " + "{" + $1.description + "}" }
            descString += "}"
        }
        descString += ", "
        if self._bottomLines.isEmpty {
            descString += "bottomLines={}"
        } else {
            let first = "{" + self.bottomLines.0.description + "}"
            descString += "bottomLines={"
            descString += self._bottomLines.dropFirst().reduce("\(first)") { $0 + ", " + "{" + $1.description + "}" }
            descString += "}"
        }
        descString += ", "
        descString += "numTopLines=\(self.numTopLines)"
        descString += ", "
        descString += "numBottomLines=\(self.numBottomLines)"
        descString += ", "
        descString += "frameNumber=\(self.frameNumber)"
        return descString
    }

}

extension wb_vision_lines: Equatable {}

public func == (lhs: wb_vision_lines, rhs: wb_vision_lines) -> Bool {
    return lhs._topLines == rhs._topLines
        && lhs._bottomLines == rhs._bottomLines
        && lhs.numTopLines == rhs.numTopLines
        && lhs.numBottomLines == rhs.numBottomLines
        && lhs.frameNumber == rhs.frameNumber
}
