/** 
 * file VisionFieldFeatures.h 
 * 
 * This file was generated by classgenerator from Vision_FieldFeatures.txt. 
 * DO NOT CHANGE MANUALLY! 
 * 
 * Created by Eugene Gilmore on 13:42, 17/7/2017 
 * Copyright (c) 2017 Eugene Gilmore 
 * All rights reserved. 
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met: 
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer. 
 * 
 * 2. Redistributions in binary form must reproduce the above 
 *    copyright notice, this list of conditions and the following 
 *    disclaimer in the documentation and/or other materials 
 *    provided with the distribution. 
 * 
 * 3. All advertising materials mentioning features or use of this 
 *    software must display the following acknowledgement: 
 * 
 *    This product includes software developed by Eugene Gilmore. 
 * 
 * 4. Neither the name of the author nor the names of contributors 
 *    may be used to endorse or promote products derived from this 
 *    software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 * 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 * ----------------------------------------------------------------------- 
 * This program is free software; you can redistribute it and/or 
 * modify it under the above terms or under the terms of the GNU 
 * General Public License as published by the Free Software Foundation; 
 * either version 2 of the License, or (at your option) any later version. 
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details. 
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, see http://www.gnu.org/licenses/ 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA  02110-1301, USA. 
 */ 


#ifndef VisionFieldFeatures_DEFINED 
#define VisionFieldFeatures_DEFINED 

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION 
#include <cstdlib> 
#include <string.h> 
#include <sstream> 
#endif 

#include "wb_vision_fieldfeatures.h" 

namespace guWhiteboard 
{
    /** 
     * @brief Posting by Vision of the field corners and T-Intersections that have been seen  
     */ 
    class VisionFieldFeatures: public wb_vision_fieldfeatures 
    { 
    public:
        /** Constructor */ 
        VisionFieldFeatures(, uint8_t numCorners = 0, uint8_t numIntersections = 0)
        { 
            set_numCorners(numCorners); 
            set_numIntersections(numIntersections); 
        } 

        /** Copy Constructor */ 
        VisionFieldFeatures(const VisionFieldFeatures &other) : wb_vision_fieldfeatures() 
        { 
            set_fieldCorner(other.fieldCorner(0), 0); 
            set_fieldCorner(other.fieldCorner(1), 1); 
            set_fieldCorner(other.fieldCorner(2), 2); 
            set_fieldCorner(other.fieldCorner(3), 3); 
            set_fieldIntersection(other.fieldIntersection(0), 0); 
            set_fieldIntersection(other.fieldIntersection(1), 1); 
            set_fieldIntersection(other.fieldIntersection(2), 2); 
            set_fieldIntersection(other.fieldIntersection(3), 3); 
            set_numCorners(other.numCorners()); 
            set_numIntersections(other.numIntersections()); 
        } 

        /** Copy Assignment Operator */ 
        VisionFieldFeatures &operator = (const VisionFieldFeatures &other) 
        { 
            set_fieldCorner(other.fieldCorner(0), 0); 
            set_fieldCorner(other.fieldCorner(1), 1); 
            set_fieldCorner(other.fieldCorner(2), 2); 
            set_fieldCorner(other.fieldCorner(3), 3); 
            set_fieldIntersection(other.fieldIntersection(0), 0); 
            set_fieldIntersection(other.fieldIntersection(1), 1); 
            set_fieldIntersection(other.fieldIntersection(2), 2); 
            set_fieldIntersection(other.fieldIntersection(3), 3); 
            set_numCorners(other.numCorners()); 
            set_numIntersections(other.numIntersections()); 
            return *this; 
        } 

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION 
        /** String Constructor */ 
        VisionFieldFeatures(const std::string &str) { from_string(str.c_str()); }  

        std::string description() 
        { 
#ifdef USE_WB_VISION_FIELDFEATURES_C_CONVERSION 
            char buffer[VISION_FIELDFEATURES_DESC_BUFFER_SIZE]; 
            wb_vision_fieldfeatures_description(this, buffer, sizeof(buffer)); 
            std::string descr = buffer; 
            return descr; 
#else 
            std::ostringstream ss; 

            bool fieldCorner_first = true; 
            ss << "fieldCorner={"; 
            for (int i = 0; i < VISION_FIELDFEATURES_FIELDCORNER_ARRAY_SIZE; i++) 
            { 
                ss << (fieldCorner_first ? "" : ",") << static_cast<Point2d *>(&fieldCorner(i))->description(); 
                fieldCorner_first = false;  
            } 
            ss << "}"; 
            ss << ", "; 

            bool fieldIntersection_first = true; 
            ss << "fieldIntersection={"; 
            for (int i = 0; i < VISION_FIELDFEATURES_FIELDINTERSECTION_ARRAY_SIZE; i++) 
            { 
                ss << (fieldIntersection_first ? "" : ",") << static_cast<Point2d *>(&fieldIntersection(i))->description(); 
                fieldIntersection_first = false;  
            } 
            ss << "}"; 
            ss << ", "; 
            ss << "numCorners=" << numCorners(); 
            ss << ", "; 
            ss << "numIntersections=" << numIntersections(); 

            return ss.str(); 

#endif /// USE_WB_VISION_FIELDFEATURES_C_CONVERSION
        } 

        std::string to_string() 
        { 
#ifdef USE_WB_VISION_FIELDFEATURES_C_CONVERSION 
            char buffer[VISION_FIELDFEATURES_DESC_BUFFER_SIZE]; 
            wb_vision_fieldfeatures_to_string(this, buffer, sizeof(buffer)); 
            std::string toString = buffer; 
            return toString; 
#else 
            std::ostringstream ss; 

            bool fieldCorner_first = true; 
            ss << "fieldCorner={"; 
            for (int i = 0; i < VISION_FIELDFEATURES_FIELDCORNER_ARRAY_SIZE; i++) 
            { 
                ss << (fieldCorner_first ? "" : ",") << static_cast<Point2d *>(&fieldCorner(i))->to_string(); 
                fieldCorner_first = false;  
            } 
            ss << "}"; 
            ss << ", "; 

            bool fieldIntersection_first = true; 
            ss << "fieldIntersection={"; 
            for (int i = 0; i < VISION_FIELDFEATURES_FIELDINTERSECTION_ARRAY_SIZE; i++) 
            { 
                ss << (fieldIntersection_first ? "" : ",") << static_cast<Point2d *>(&fieldIntersection(i))->to_string(); 
                fieldIntersection_first = false;  
            } 
            ss << "}"; 
            ss << ", "; 
            ss << numCorners(); 
            ss << ", "; 
            ss << numIntersections(); 

            return ss.str(); 

#endif /// USE_WB_VISION_FIELDFEATURES_C_CONVERSION
        } 

        void from_string(const std::string &str) 
        { 
#ifdef USE_WB_VISION_FIELDFEATURES_C_CONVERSION 
            wb_vision_fieldfeatures_from_string(this, str); 
#else 
            char var[100]; 
            unsigned long fieldCorner_index = str.find("fieldCorner");
            if(fieldCorner_index != std::string::npos)
            {
                memset(&var[0], 0, sizeof(var));
                if(sscanf(str.substr(fieldCorner_index, str.length()).c_str(), "fieldCorner = %[^,]", var) == 1)
                {
                    std::string value = std::string(var);
                } 
            } 

            unsigned long fieldIntersection_index = str.find("fieldIntersection");
            if(fieldIntersection_index != std::string::npos)
            {
                memset(&var[0], 0, sizeof(var));
                if(sscanf(str.substr(fieldIntersection_index, str.length()).c_str(), "fieldIntersection = %[^,]", var) == 1)
                {
                    std::string value = std::string(var);
                } 
            } 

            unsigned long numCorners_index = str.find("numCorners");
            if(numCorners_index != std::string::npos)
            {
                memset(&var[0], 0, sizeof(var));
                if(sscanf(str.substr(numCorners_index, str.length()).c_str(), "numCorners = %[^,]", var) == 1)
                {
                    std::string value = std::string(var);
                    set_numCorners(uint8_t(atoi(value.c_str()))); 
                } 
            } 

            unsigned long numIntersections_index = str.find("numIntersections");
            if(numIntersections_index != std::string::npos)
            {
                memset(&var[0], 0, sizeof(var));
                if(sscanf(str.substr(numIntersections_index, str.length()).c_str(), "numIntersections = %[^,]", var) == 1)
                {
                    std::string value = std::string(var);
                    set_numIntersections(uint8_t(atoi(value.c_str()))); 
                } 
            } 

#endif /// USE_WB_VISION_FIELDFEATURES_C_CONVERSION
        } 
#endif ///   WHITEBOARD_POSTER_STRING_CONVERSION
    }; 
} /// namespace guWhiteboard 
#endif /// VisionFieldFeatures_DEFINED 
