/** 
 * file wb_sensors_bodysensors.c 
 * 
 * This file was generated by classgenerator from SENSORS_BodySensors.txt. 
 * DO NOT CHANGE MANUALLY! 
 * 
 * Created by Carl Lusty at 16:25, 22/12/2015 
 * Copyright (c) 2015 Carl Lusty 
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met: 
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer. 
 * 
 * 2. Redistributions in binary form must reproduce the above 
 *    copyright notice, this list of conditions and the following 
 *    disclaimer in the documentation and/or other materials 
 *    provided with the distribution. 
 * 
 * 3. All advertising materials mentioning features or use of this 
 *    software must display the following acknowledgement: 
 * 
 *    This product includes software developed by Carl Lusty. 
 * 
 * 4. Neither the name of the author nor the names of contributors 
 *    may be used to endorse or promote products derived from this 
 *    software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 * 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 * ----------------------------------------------------------------------- 
 * This program is free software; you can redistribute it and/or 
 * modify it under the above terms or under the terms of the GNU 
 * General Public License as published by the Free Software Foundation; 
 * either version 2 of the License, or (at your option) any later version. 
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details. 
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, see http://www.gnu.org/licenses/ 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA  02110-1301, USA. 
 */ 


#include "wb_sensors_bodysensors.h" 
#include <stdio.h> 
#include <string.h> 
#include <stdlib.h> 

/** convert to a description string */  
const char* wb_sensors_bodysensors_description(const struct wb_sensors_bodysensors* self, char* descString, size_t bufferSize) 
{ 
    size_t len; 

    snprintf(descString+len, bufferSize-len, "InertialSensor_AccX=%f", self->InertialSensor_AccX); 
    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_AccY=%f", self->InertialSensor_AccY); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_AccZ=%f", self->InertialSensor_AccZ); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_GyrX=%f", self->InertialSensor_GyrX); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_GyrY=%f", self->InertialSensor_GyrY); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_GyrRef=%f", self->InertialSensor_GyrRef); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_AngleX=%f", self->InertialSensor_AngleX); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "InertialSensor_AngleY=%f", self->InertialSensor_AngleY); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "Battery_Charge        =%f", self->Battery_Charge        ); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "Battery_Current       =%f", self->Battery_Current       ); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "US                    =%f", self->US                    ); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        gu_strlcat(descString, "ChestBoard_Button      =", bufferSize); 
        gu_strlcat(descString, self->ChestBoard_Button       ? "true" : "false", bufferSize); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        gu_strlcat(descString, "pad1;=", bufferSize); 
        gu_strlcat(descString, self->pad1; ? "true" : "false", bufferSize); 
    } 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(descString+len, bufferSize-len, "pad2;=%d", self->pad2;); 
    } 

	return descString; 
} 

/** convert to a string */  
const char* wb_sensors_bodysensors_to_string(const struct wb_sensors_bodysensors* self, char* toString, size_t bufferSize) 
{ 
    size_t len; 

    snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_AccX); 
    len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_AccY); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_AccZ); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_GyrX); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_GyrY); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_GyrRef); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_AngleX); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->InertialSensor_AngleY); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->Battery_Charge        ); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->Battery_Current       ); 
    } 

     len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%f", self->US                    ); 
    } 

     gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        gu_strlcat(toString, self->ChestBoard_Button       ? "true" : "false", bufferSize); 

    } 

    gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        gu_strlcat(toString, self->pad1; ? "true" : "false", bufferSize); 

    } 

    len = gu_strlcat(toString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        snprintf(toString+len, bufferSize-len, "%d", self->pad2;); 
    } 

     return toString; 
} 

/** convert from a string */  
struct wb_sensors_bodysensors* wb_sensors_bodysensors_from_string(struct wb_sensors_bodysensors* self, const char* str) 
{ 
    char* strings[SENSORS_BODYSENSORS_NUMBER_OF_VARIABLES]; 
    memset(strings, 0, sizeof(strings)); 
    char* saveptr; 
    int count = 0; 

    char* str_copy = gu_strdup(str); 

    const char s[2] = ",";   /// delimeter 
    const char e = '=';      /// delimeter 
    char* tokenS, *tokenE; 

    tokenS = strtok_r(str_copy, s, &saveptr); 

    while (tokenS != NULL) 
    { 
        tokenE = strchr(tokenS, e); 

        if (tokenE == NULL) 
        { 
             tokenE = tokenS; 
        } 
        else 
        { 
             tokenE++; 
        } 

        strings[count] = gu_strtrim(tokenE); 

        count++; 
        tokenS = strtok_r(NULL, s, &saveptr); 
    } 

    if (strings[0] != NULL) 
       self->InertialSensor_AccX = (float)atof(strings[0]); 

    if (strings[1] != NULL) 
       self->InertialSensor_AccY = (float)atof(strings[1]); 

    if (strings[2] != NULL) 
       self->InertialSensor_AccZ = (float)atof(strings[2]); 

    if (strings[3] != NULL) 
       self->InertialSensor_GyrX = (float)atof(strings[3]); 

    if (strings[4] != NULL) 
       self->InertialSensor_GyrY = (float)atof(strings[4]); 

    if (strings[5] != NULL) 
       self->InertialSensor_GyrRef = (float)atof(strings[5]); 

    if (strings[6] != NULL) 
       self->InertialSensor_AngleX = (float)atof(strings[6]); 

    if (strings[7] != NULL) 
       self->InertialSensor_AngleY = (float)atof(strings[7]); 

    if (strings[8] != NULL) 
       self->Battery_Charge         = (float)atof(strings[8]); 

    if (strings[9] != NULL) 
       self->Battery_Current        = (float)atof(strings[9]); 

    if (strings[10] != NULL) 
       self->US                     = (float)atof(strings[10]); 

    if (strings[11] != NULL) 
       self->ChestBoard_Button       = strcmp(strings[11], "true") == 0  || strcmp(strings[11], "1") == 0 ? true : false; 

    if (strings[12] != NULL) 
       self->pad1; = strcmp(strings[12], "true") == 0  || strcmp(strings[12], "1") == 0 ? true : false; 

    if (strings[13] != NULL) 
       self->pad2; = (int16_t)atoi(strings[13]); 

    free(str_copy); 

    return self; 
}; 
