/** 
 * file wb_vision_fieldfeatures.h 
 * 
 * This file was generated by classgenerator from Vision_FieldFeatures.txt. 
 * DO NOT CHANGE MANUALLY! 
 * 
 * Created by Eugene Gilmore at 16:53, 17/7/2017 
 * Copyright (c) 2017 Eugene Gilmore 
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met: 
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer. 
 * 
 * 2. Redistributions in binary form must reproduce the above 
 *    copyright notice, this list of conditions and the following 
 *    disclaimer in the documentation and/or other materials 
 *    provided with the distribution. 
 * 
 * 3. All advertising materials mentioning features or use of this 
 *    software must display the following acknowledgement: 
 * 
 *    This product includes software developed by Eugene Gilmore. 
 * 
 * 4. Neither the name of the author nor the names of contributors 
 *    may be used to endorse or promote products derived from this 
 *    software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 * 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 * ----------------------------------------------------------------------- 
 * This program is free software; you can redistribute it and/or 
 * modify it under the above terms or under the terms of the GNU 
 * General Public License as published by the Free Software Foundation; 
 * either version 2 of the License, or (at your option) any later version. 
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details. 
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, see http://www.gnu.org/licenses/ 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA  02110-1301, USA. 
 */ 


#ifndef wb_vision_fieldfeatures_h 
#define wb_vision_fieldfeatures_h 

#include "gu_util.h" 

#include <stdint.h> 
#include "wb_vision_fieldfeature.h"

#define VISION_FIELDFEATURES_NUMBER_OF_VARIABLES 4 

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION 
#define VISION_FIELDFEATURES_DESC_BUFFER_SIZE 581 
#define VISION_FIELDFEATURES_TO_STRING_BUFFER_SIZE 523 
#endif /// WHITEBOARD_POSTER_STRING_CONVERSION 

#define VISION_FIELDFEATURES_FIELDCORNER_ARRAY_SIZE 8 
#define VISION_FIELDFEATURES_FIELDINTERSECTION_ARRAY_SIZE 8 

/** 
 * @brief Posting by Vision of the field corners and T-Intersections that have been seen  
 */ 
struct wb_vision_fieldfeatures 
{ 
    /** location of corners on the field */ 
    ARRAY_PROPERTY(struct wb_vision_fieldfeature, fieldCorner, VISION_FIELDFEATURES_FIELDCORNER_ARRAY_SIZE)

    /** location of T-Intersections on the field */ 
    ARRAY_PROPERTY(struct wb_vision_fieldfeature, fieldIntersection, VISION_FIELDFEATURES_FIELDINTERSECTION_ARRAY_SIZE)

    /** number of corners in this message */ 
    PROPERTY(uint8_t, numCorners) 

    /** number of T-Intersections in this message */ 
    PROPERTY(uint8_t, numIntersections) 

}; 

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION 
/** convert to a description string */  
const char* wb_vision_fieldfeatures_description(const struct wb_vision_fieldfeatures* self, char* descString, size_t bufferSize); 

/** convert to a string */  
const char* wb_vision_fieldfeatures_to_string(const struct wb_vision_fieldfeatures* self, char* toString, size_t bufferSize); 

/** convert from a string */  
struct wb_vision_fieldfeatures* wb_vision_fieldfeatures_from_string(struct wb_vision_fieldfeatures* self, const char* str); 
#endif /// WHITEBOARD_POSTER_STRING_CONVERSION 

#endif /// wb_vision_fieldfeatures_h 
